Repository gizmokis/resin, pull requests merged in 2024-11, with the labels that each got.

#7 [SDF-20] Automatic Semantic Versioning
  .github/workflows/pull-request-labeler.yml
  .github/workflows/pull-request-tagger.yml
Labels: size/M 🐂, version/patch 🪶

#2 [SDF-23] Transform class
  .idea/codeStyles/Project.xml
  libresin/CMakeLists.txt
  libresin/libresin/core/transform.cpp
  libresin/libresin/core/transform.hpp
  libresin/tests/core/transform_test.cpp
  libresin/tests/glm_helper.hpp
Labels: size/L 🦑, version/minor 🔨

#8 [SDF-22] Logger
  .clang-format
  .clang-tidy
  .gitignore
  cmake/version.hpp.in
  libresin/CMakeLists.txt
  libresin/libresin/core/transform.hpp
  libresin/libresin/utils/logger.cpp
  libresin/libresin/utils/logger.hpp
  libresin/tests/core/transform_test.cpp
  resin/resin/main.cpp
Labels: size/L 🦑, version/minor 🔨

#10 [SDF-69] Fix CMake repo version not found issue
  .github/workflows/pull-request-tagger.yml
  cmake/find_repo_version.cmake
Labels: version/patch 🪶

#11 [SDF-70] Fix checkout action
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: version/patch 🪶

#9 [SDF-65] Basic window and application functionality
  .clang-tidy
  libresin/CMakeLists.txt
  libresin/libresin/core/transform.hpp
  libresin/libresin/resin.cpp
  libresin/libresin/resin.hpp
  resin/CMakeLists.txt
  resin/resin/core/graphics_context.cpp
  resin/resin/core/graphics_context.hpp
  resin/resin/core/window.cpp
  resin/resin/core/window.hpp
  resin/resin/event/event.hpp
  resin/resin/event/window_events.hpp
  resin/resin/main.cpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/L 🦑, version/minor 🔨

#12 [SDF-64] Add ShaderResource with preprocessing
  .clang-tidy
  CMakeLists.txt
  cmake/test_consts.hpp.in
  libresin/CMakeLists.txt
  libresin/libresin/core/resources/resource_manager.hpp
  libresin/libresin/core/resources/shader_resource.cpp
  libresin/libresin/core/resources/shader_resource.hpp
  libresin/libresin/core/transform.cpp
  libresin/libresin/core/transform.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/libresin/utils/logger.cpp
  libresin/libresin/utils/logger.hpp
  libresin/tests/core/resources/shader_resource_test.cpp
  libresin/tests/core/transform_test.cpp
  libresin/tests/data/core/resources/deps_cycle/main.vert
  libresin/tests/data/core/resources/deps_cycle/shader_a.glsl
  libresin/tests/data/core/resources/deps_cycle/shader_b.glsl
  libresin/tests/data/core/resources/deps_cycle/shader_c.glsl
  libresin/tests/data/core/resources/invalid_ext.frg
  libresin/tests/data/core/resources/regular_load/expected_glsl.frag
  libresin/tests/data/core/resources/regular_load/expected_raw.frag
  libresin/tests/data/core/resources/regular_load/main.frag
  libresin/tests/data/core/resources/regular_load/shader_a.glsl
  libresin/tests/data/core/resources/regular_load/shader_b.glsl
  libresin/tests/data/core/resources/regular_load/shader_c.glsl
  libresin/tests/example_test.cpp
  libresin/tests/files_helper.hpp
  libresin/tests/glm_helper.hpp
  resin/CMakeLists.txt
  resin/resin/core/graphics_context.cpp
  resin/resin/core/window.cpp
  resin/resin/core/window.hpp
  resin/resin/event/window_events.hpp
  resin/resin/main.cpp
  resin/resin/resin.cpp
Labels: version/minor 🔨

#13 [SDF-25] Camera Class
  libresin/CMakeLists.txt
  libresin/libresin/core/camera.cpp
  libresin/libresin/core/camera.hpp
  libresin/tests/core/camera_test.cpp
Labels: size/M 🐂, version/minor 🔨

#15 [SDF-80] Add compute shader resource and versions support
  libresin/libresin/core/resources/shader_resource.cpp
  libresin/libresin/core/resources/shader_resource.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/libresin/utils/string_views.hpp
  libresin/tests/data/core/resources/deps_cycle/main.vert
  libresin/tests/data/core/resources/regular_load/main.frag
Labels: size/M 🐂, version/minor 🔨

#14 [SDF-28][SDF-30] Shader program
  .clang-tidy
  .github/workflows/formatter-linter-tests.yml
  cmake/copy_assets.cmake
  libresin/CMakeLists.txt
  libresin/libresin/core/resources/shader_resource.cpp
  libresin/libresin/core/resources/shader_resource.hpp
  libresin/libresin/core/shader.cpp
  libresin/libresin/core/shader.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/libresin/utils/string_hash.hpp
  libresin/libresin/utils/string_views.hpp
  libresin/tests/core/resources/shader_resource_test.cpp
  libresin/tests/data/core/resources/deps_cycle/main.vert
  libresin/tests/data/core/resources/regular_load/expected_glsl.frag
  libresin/tests/data/core/resources/regular_load/main.frag
  libresin/tests/files_helper.hpp
  resin/CMakeLists.txt
  resin/assets/test.frag
  resin/assets/test.vert
  resin/resin/core/window.cpp
  resin/resin/event/event.hpp
  resin/resin/event/window_events.hpp
  resin/resin/main.cpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/XL 🐋, version/minor 🔨

#17 [BUGFIX] remove unused uniform
  resin/assets/test.frag
  resin/resin/resin.cpp
Labels: version/patch 🪶

#16 [SDF-85] Add simple imgui integration
  cmake/dependencies/CMakeLists.txt
  patches/imgui.patch
  resin/resin/core/window.cpp
  resin/resin/resin.cpp
Labels: version/minor 🔨

#18 Use recursive cpp files search
  libresin/CMakeLists.txt
  resin/CMakeLists.txt
Labels: size/S 🐇, version/patch 🪶

#19 [SDF-75] Transform ImGui component
  .clang-tidy
  libresin/libresin/core/transform.cpp
  libresin/libresin/core/transform.hpp
  libresin/tests/core/transform_test.cpp
  resin/assets/test.frag
  resin/resin/core/window.cpp
  resin/resin/core/window.hpp
  resin/resin/imgui/components.cpp
  resin/resin/imgui/components.hpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/M 🐂, version/minor 🔨
