Repository gizmokis/resin, pull requests merged in 2024-12, with the labels that each got.

#21 [SDF-36] Blinn-Phong
  resin/assets/blinn_phong.glsl
  resin/assets/sdf.glsl
  resin/assets/test.frag
Labels: size/M 🐂, version/patch 🪶

#23 [SDF-26] Basic light structs
  libresin/libresin/core/light.hpp
  libresin/libresin/core/shader.hpp
  resin/assets/test.frag
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/M 🐂, version/minor 🔨

#22 [SDF-63] SDF Tree system
  .clang-tidy
  libresin/libresin/core/id_registry.hpp
  libresin/libresin/core/resources/shader_resource.cpp
  libresin/libresin/core/sdf_shader_consts.hpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/group_node.hpp
  libresin/libresin/core/sdf_tree/primitive_node.cpp
  libresin/libresin/core/sdf_tree/primitive_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.cpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node_visitor.hpp
  libresin/libresin/core/transform.hpp
  libresin/libresin/utils/enum_mapper.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/libresin/utils/logger.hpp
  libresin/tests/core/sdf_tree/sdf_tree_test.cpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
  resin/resin/imgui/transform_edit.cpp
  resin/resin/imgui/transform_edit.hpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/XL 🐋, version/minor 🔨

#24 [SDF-95] Include assets in release
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: version/patch 🪶

#25 [SDF-27] Basic material struct
  libresin/libresin/core/material.hpp
  libresin/libresin/core/shader.hpp
  resin/assets/test.frag
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/S 🐇, version/minor 🔨

#27 [SDF-94] [SDF-51] [SDF-101] Add assimp, nlohmann/json dependencies and all licenses
  CMakeLists.txt
  LICENSE
  THIRD_PARTY_LICENSES/assimp_LICENSE
  THIRD_PARTY_LICENSES/glad_LICENSE
  THIRD_PARTY_LICENSES/glfw_LICENSE
  THIRD_PARTY_LICENSES/glm_LICENSE
  THIRD_PARTY_LICENSES/googletest_LICENSE
  THIRD_PARTY_LICENSES/imgui_LICENSE
  THIRD_PARTY_LICENSES/nlohmann_json_LICENSE
  cmake/dependencies/CMakeLists.txt
  libresin/CMakeLists.txt
  resin/resin/main.cpp
Labels: version/patch 🪶

#26 [SDF-90] SDF tree component
  CMakePresets.json
  libresin/libresin/core/camera.cpp
  libresin/libresin/core/id_registry.hpp
  libresin/libresin/core/light.hpp
  libresin/libresin/core/sdf_shader_consts.hpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/group_node.hpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/primitive_node.cpp
  libresin/libresin/core/sdf_tree/primitive_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.cpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node_visitor.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_registry.hpp
  libresin/libresin/utils/enum_mapper.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/tests/core/camera_test.cpp
  libresin/tests/core/transform_test.cpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/L 🦑, version/minor 🔨

#28 [SDF-99] Global style for the project
  resin/assets/fonts/OpenSans-Bold.ttf
  resin/assets/fonts/OpenSans-Regular.ttf
  resin/assets/test.frag
  resin/resin/core/window.cpp
  resin/resin/core/window.hpp
  resin/resin/imgui/sdf_tree.cpp
Labels: size/M 🐂, version/patch 🪶

#29 [SDF-97] Uniform Buffer Object
  libresin/libresin/core/sdf_shader_consts.hpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/group_node.hpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_registry.hpp
  libresin/libresin/core/shader.cpp
  libresin/libresin/core/shader.hpp
  libresin/libresin/core/uniform_buffer.cpp
  libresin/libresin/core/uniform_buffer.hpp
  libresin/tests/core/sdf_tree/sdf_tree_test.cpp
  resin/assets/sdf.glsl
  resin/assets/test.frag
  resin/resin/core/window.cpp
  resin/resin/imgui/node_edit.cpp
  resin/resin/imgui/node_edit.hpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/L 🦑, version/minor 🔨

#32 [SDF-46] Group (prefab) export/import backend
  THIRD_PARTY_LICENSES/valijson_LICENSE
  cmake/dependencies/CMakeLists.txt
  cmake/inject_defs_into_schema.cmake
  cmake/json_schemas.hpp.in
  libresin/CMakeLists.txt
  libresin/libresin/core/material.hpp
  libresin/libresin/core/sdf_shader_consts.hpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/group_node.hpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  libresin/libresin/utils/enum_mapper.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/libresin/utils/json.cpp
  libresin/libresin/utils/json.hpp
  libresin/tests/files_helper.hpp
  libresin/tests/random_helper.hpp
  libresin/tests/utils/json_tests.cpp
  patches/valijson.patch
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
  schemas/definitions.schema.json
  schemas/prefab.schema.json
Labels: size/XL 🐋, version/minor 🔨

#31 [SDF-96] Materials and SDF tree integration
  .clang-tidy
  THIRD_PARTY_LICENSES/valijson_LICENSE
  cmake/dependencies/CMakeLists.txt
  cmake/inject_defs_into_schema.cmake
  cmake/json_schemas.hpp.in
  libresin/CMakeLists.txt
  libresin/libresin/core/id_registry.hpp
  libresin/libresin/core/material.cpp
  libresin/libresin/core/material.hpp
  libresin/libresin/core/sdf_shader_consts.hpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/group_node.hpp
  libresin/libresin/core/sdf_tree/primitive_base_node.cpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_registry.hpp
  libresin/libresin/utils/enum_mapper.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/libresin/utils/json.cpp
  libresin/libresin/utils/json.hpp
  libresin/tests/core/sdf_tree/sdf_tree_test.cpp
  libresin/tests/files_helper.hpp
  libresin/tests/random_helper.hpp
  libresin/tests/utils/json_tests.cpp
  patches/valijson.patch
  resin/resin/imgui/node_edit.cpp
  resin/resin/imgui/node_edit.hpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
  schemas/definitions.schema.json
  schemas/prefab.schema.json
Labels: size/L 🦑, version/minor 🔨
