Repository gizmokis/resin, pull requests merged in 2025-01, with the labels that each got.

#34 [SDF-81][SDF-108] Framebuffer
  libresin/libresin/core/framebuffer.hpp
  libresin/libresin/core/framebufffer.cpp
  libresin/libresin/utils/exceptions.hpp
  resin/resin/imgui/viewport.cpp
  resin/resin/imgui/viewport.hpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/M 🐂, version/patch 🪶

#33 [SDF-122] Open/save file dialog for prefabs
  .github/workflows/formatter-linter-tests.yml
  .github/workflows/linux.yml
  THIRD_PARTY_LICENSES/nfd_LICENSE
  cmake/dependencies/CMakeLists.txt
  libresin/libresin/core/resources/shader_resource.cpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/group_node.hpp
  libresin/libresin/core/sdf_tree/primitive_base_node.cpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_registry.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/libresin/utils/path_utf.cpp
  libresin/libresin/utils/path_utf.hpp
  libresin/tests/core/sdf_tree/sdf_tree_test.cpp
  patches/nfd.patch
  resin/CMakeLists.txt
  resin/assets/sdf.glsl
  resin/resin/core/window.cpp
  resin/resin/dialog/file_dialog.cpp
  resin/resin/dialog/file_dialog.hpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
  resin/resin/resin.cpp
Labels: size/L 🦑, version/minor 🔨

#36 Fix dirty primitives
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.cpp
  libresin/libresin/core/sdf_tree/sdf_tree_registry.hpp
Labels: version/patch 🪶

#37 [SDF-111] Add translation/rotation/scale gizmo
  THIRD_PARTY_LICENSES/imguizmo_LICENSE
  cmake/dependencies/CMakeLists.txt
  libresin/libresin/core/camera.cpp
  libresin/libresin/core/camera.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/transform.cpp
  libresin/libresin/core/transform.hpp
  patches/imguizmo.patch
  resin/CMakeLists.txt
  resin/assets/test.frag
  resin/assets/test.vert
  resin/resin/core/window.cpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
  resin/resin/imgui/transform_gizmo.cpp
  resin/resin/imgui/transform_gizmo.hpp
  resin/resin/imgui/viewport.cpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/M 🐂, version/minor 🔨

#35 [SDF-109] Mouse picking
  .github/workflows/formatter-linter-tests.yml
  libresin/libresin/core/camera.cpp
  libresin/libresin/core/camera.hpp
  libresin/libresin/core/framebuffer.hpp
  libresin/libresin/core/framebufffer.cpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/shader.cpp
  libresin/libresin/core/shader.hpp
  libresin/libresin/core/uniform_buffer.cpp
  libresin/libresin/core/uniform_buffer.hpp
  libresin/libresin/utils/enum_mapper.hpp
  libresin/tests/core/camera_test.cpp
  libresin/tests/core/sdf_tree/sdf_tree_test.cpp
  patches/imguizmo.patch
  resin/assets/blinn_phong.glsl
  resin/assets/sdf.glsl
  resin/assets/test.frag
  resin/assets/test.vert
  resin/resin/core/mouse_codes.hpp
  resin/resin/core/window.cpp
  resin/resin/event/event.hpp
  resin/resin/event/mouse_events.hpp
  resin/resin/event/window_events.hpp
  resin/resin/imgui/transform_gizmo.cpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/L 🦑, version/minor 🔨

#38 [SDF-42][SDF-45] Baking and exporting mesh
  libresin/CMakeLists.txt
  libresin/libresin/core/mesh_exporter.cpp
  libresin/libresin/core/mesh_exporter.hpp
  libresin/libresin/core/resources/shader_resource.hpp
  libresin/libresin/core/shader.cpp
  libresin/libresin/core/shader.hpp
  libresin/libresin/core/shader_storage_buffer.cpp
  libresin/libresin/core/shader_storage_buffer.hpp
  resin/assets/marching_cubes.comp
  resin/resin/core/window.cpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/resin.hpp
  resin/resin/resources/resource_managers.hpp
Labels: size/L 🦑, version/minor 🔨

#40 [SDF-82] Add camera
  libresin/libresin/core/transform.cpp
  libresin/libresin/core/transform.hpp
  libresin/libresin/utils/enum_mapper.hpp
  patches/imguizmo.patch
  resin/resin/camera/first_person_camera_operator.cpp
  resin/resin/camera/first_person_camera_operator.hpp
  resin/resin/camera/orbiting_camera_operator.cpp
  resin/resin/camera/orbiting_camera_operator.hpp
  resin/resin/core/key_codes.hpp
  resin/resin/core/mouse_codes.hpp
  resin/resin/core/window.cpp
  resin/resin/core/window.hpp
  resin/resin/event/event.hpp
  resin/resin/event/key_events.hpp
  resin/resin/event/mouse_events.hpp
  resin/resin/imgui/gizmo.cpp
  resin/resin/imgui/gizmo.hpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/transform_gizmo.hpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/XL 🐋, version/minor 🔨

#41 [SDF-116] Proper depth and depth testing
  libresin/libresin/core/framebuffer.hpp
  libresin/libresin/core/framebufffer.cpp
  libresin/libresin/core/raycaster.cpp
  libresin/libresin/core/raycaster.hpp
  resin/assets/grid.frag
  resin/assets/main.frag
  resin/assets/main.vert
  resin/resin/core/window.cpp
  resin/resin/event/event.hpp
  resin/resin/event/mouse_events.hpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/M 🐂, version/patch 🪶

#42 [HOTFIX] Fix camera up/down issues
  resin/resin/camera/first_person_camera_operator.cpp
  resin/resin/resin.cpp
Labels: version/patch 🪶

#43 [SDF-29] Add missing primitives
  libresin/libresin/core/sdf_shader_consts.hpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/primitive_node.cpp
  libresin/libresin/core/sdf_tree/primitive_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node_visitor.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_registry.hpp
  libresin/libresin/core/shader.cpp
  libresin/libresin/core/uniform_buffer.cpp
  libresin/libresin/core/uniform_buffer.hpp
  libresin/libresin/utils/json.cpp
  libresin/libresin/utils/json.hpp
  libresin/tests/glm_helper.hpp
  libresin/tests/utils/json_tests.cpp
  resin/assets/blinn_phong.glsl
  resin/assets/sdf.glsl
  resin/resin/imgui/node_edit.cpp
  resin/resin/imgui/node_edit.hpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
  schemas/definitions.schema.json
Labels: size/XL 🐋, version/minor 🔨

#44 [SDF-136][SDF-131] Materials inspector + node material shader integration
  libresin/libresin/core/framebuffer.hpp
  libresin/libresin/core/framebufffer.cpp
  libresin/libresin/core/material.cpp
  libresin/libresin/core/material.hpp
  libresin/libresin/core/mesh_exporter.cpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_registry.hpp
  libresin/libresin/core/shader.cpp
  libresin/libresin/core/shader.hpp
  libresin/libresin/core/uniform_buffer.cpp
  libresin/libresin/core/uniform_buffer.hpp
  resin/assets/blinn_phong.glsl
  resin/assets/main.frag
  resin/assets/material_view.frag
  resin/assets/sdf.glsl
  resin/resin/core/graphics_context.cpp
  resin/resin/dialog/file_dialog.cpp
  resin/resin/imgui/dnd_payloads.hpp
  resin/resin/imgui/gizmo.hpp
  resin/resin/imgui/material.cpp
  resin/resin/imgui/material.hpp
  resin/resin/imgui/node_edit.cpp
  resin/resin/imgui/node_edit.hpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
  resin/resin/imgui/transform_edit.hpp
  resin/resin/imgui/types.hpp
  resin/resin/imgui/viewport.cpp
  resin/resin/imgui/viewport.hpp
  resin/resin/main.cpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
Labels: size/XL 🐋, version/minor 🔨

#45 [SDF-120] All binary operations
  libresin/libresin/core/sdf_tree/sdf_tree_node.cpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  resin/assets/sdf.glsl
Labels: size/S 🐇, version/minor 🔨

#46 [SDF-137] Allow empty scene
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  resin/assets/sdf.glsl
Labels: size/XS 🦔, version/patch 🪶

#47 [SDF-152] Improve popup menu
  .github/workflows/formatter-linter-tests.yml
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/primitive_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.cpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  libresin/libresin/core/transform.cpp
  libresin/libresin/core/transform.hpp
  patches/imgui.patch
  resin/resin/imgui/material.cpp
  resin/resin/imgui/modals.cpp
  resin/resin/imgui/modals.hpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/imgui/sdf_tree.hpp
Labels: size/M 🐂, version/minor 🔨

#48 [SDF-117][SDF-126] Proper node attribute handling
  libresin/libresin/core/mesh_exporter.cpp
  libresin/libresin/core/sdf_shader_consts.hpp
  libresin/libresin/core/sdf_tree/group_node.cpp
  libresin/libresin/core/sdf_tree/group_node.hpp
  libresin/libresin/core/sdf_tree/primitive_base_node.cpp
  libresin/libresin/core/sdf_tree/primitive_base_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.cpp
  libresin/libresin/core/sdf_tree/sdf_tree_node.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_node_visitor.hpp
  libresin/libresin/core/sdf_tree/sdf_tree_registry.hpp
  libresin/libresin/core/transform.cpp
  libresin/libresin/core/transform.hpp
  libresin/libresin/core/uniform_buffer.cpp
  libresin/libresin/core/uniform_buffer.hpp
  libresin/libresin/utils/json.cpp
  libresin/libresin/utils/json.hpp
  libresin/tests/core/sdf_tree/sdf_tree_test.cpp
  resin/assets/main.frag
  resin/assets/marching_cubes.comp
  resin/assets/sdf.glsl
  resin/resin/imgui/node_edit.cpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
  schemas/definitions.schema.json
Labels: size/M 🐂, version/patch 🪶

#49 [SDF-43][SDF-104][SDF-141] Export/import scene
  .vscode/launch.json
  CMakePresets.json
  cmake/json_schemas.hpp.in
  libresin/CMakeLists.txt
  libresin/libresin/core/id_registry.hpp
  libresin/libresin/core/light.hpp
  libresin/libresin/core/mesh_exporter.cpp
  libresin/libresin/core/scene.cpp
  libresin/libresin/core/scene.hpp
  libresin/libresin/core/sdf_tree/sdf_tree.cpp
  libresin/libresin/core/sdf_tree/sdf_tree.hpp
  libresin/libresin/utils/exceptions.hpp
  libresin/libresin/utils/json.cpp
  libresin/libresin/utils/json.hpp
  libresin/libresin/utils/macros.hpp
  libresin/libresin/utils/path.cpp
  libresin/libresin/utils/path.hpp
  libresin/libresin/utils/string_views.hpp
  libresin/tests/utils/json_tests.cpp
  resin/resin/core/window.cpp
  resin/resin/core/window.hpp
  resin/resin/dialog/file_dialog.cpp
  resin/resin/imgui/main_menu_bar.cpp
  resin/resin/imgui/main_menu_bar.hpp
  resin/resin/imgui/material.hpp
  resin/resin/imgui/modals.cpp
  resin/resin/imgui/modals.hpp
  resin/resin/imgui/sdf_tree.cpp
  resin/resin/main.cpp
  resin/resin/resin.cpp
  resin/resin/resin.hpp
  schemas/definitions.schema.json
  schemas/scene.schema.json
Labels: size/L 🦑, version/minor 🔨
